{
    "name": "Training Center",
    "summary": "Training Center management system",
    "author": "Kokhanovskyi Ivan",
    "website": "https://github.com/kokhanovskyi-i/",
    "category": "Customizations",
    "license": "OPL-1",
    "version": "19.0.1.0.0",
    "depends": [
        "base",
    ],
    "data": [
        "security/training_center_groups.xml",
        "security/ir.model.access.csv",
        "security/training_center_security_rules.xml",
        "data/subject_data.xml",
        "data/teacher_category_data.xml",
        "views/training_center_lesson_views.xml",
        "views/training_center_subject_views.xml",
        "views/training_center_teacher_views.xml",
        "views/training_center_teacher_category_views.xml",
        "views/training_center_teacher_assignment_history_views.xml",
        "views/training_center_student_views.xml",
        "views/lesson_report_wizard_views.xml",
        "report/training_center_teacher_report_templates.xml",
        "report/training_center_teacher_report.xml",
        "views/training_center_res_partner_views.xml",
        "views/training_center_res_users_views.xml",
        "views/training_center_menu.xml",
    ],
    "demo": [
        "demo/demo_data.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "images": ["static/description/icon.png"],
}
