from . import hr_hospital_medic_info
from . import hr_hospital_doctor_category
from . import hr_hospital_doctor_history
from . import hr_hospital_appointment
from . import hr_hospital_disease
from . import hr_hospital_doctor
from . import hr_hospital_patient
from . import hr_hospital_mass_reassign_doctor_wizard
from . import hr_hospital_visit_report_wizard
from . import hr_hospital_disease_report_wizard
