from . import training_center_person_info
from . import training_center_teacher_category
from . import training_center_teacher_assignment_history
from . import training_center_lesson
from . import training_center_subject
from . import training_center_teacher
from . import training_center_student
from . import training_center_mass_reassign_teacher_wizard
from . import training_center_lesson_report_wizard
from . import training_center_subject_report_wizard
from . import res_partner
from . import res_users
